# Generated by Django 5.1.6 on 2025-03-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('qualification', models.CharField(choices=[('highschool', 'High School'), ('bachelor', 'Bachelor’s Degree'), ('master', 'Master’s Degree'), ('phd', 'PhD'), ('other', 'Other')], max_length=20)),
                ('message', models.TextField()),
            ],
        ),
    ]
