# Generated by Django 5.1.6 on 2025-03-08 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_contact_name_alter_contact_qualification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='question',
        ),
    ]
